theme = "catppuccin_mocha"
[editor]
scrolloff = 10
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true