#!/bin/sh <- tmp fix for hx highlight
{
    "layer": "top",
    "position": "bottom",
    "height": 36,
    "spacing": 4,
    "modules-left": [
        "wlr/workspaces"
    ],
    "modules-center": [
        "clock"
    ],
    "modules-right": [
        "tray", 
        "custom/clipboard", 
        "idle_inhibitor", 
        "custom/weather", 
        "wireplumber", 
        "backlight", 
        "network", 
        "battery"
    ],
    "custom/clipboard": {
      "format": "🄯",
      "interval": "once",
      "return-type": "json",
      "on-click": "exec cliphist list | rofi -dmenu | cliphist decode | wl-copy",
      "signal": 9
    },
    "wlr/workspaces": {
        "format": "{icon}",
        "on-click": "activate",
        "format-icons": {
            "1": "",
            "2": "",
            "3": "",
            "4": "",
            "5": "",
            "urgent": "",
            "active": "",
            "default": ""
        },
        "sort-by-number": true
    },
    "idle_inhibitor": {
        "format": "{icon}",
        "format-icons": {
            "activated": "",
            "deactivated": ""
        }
    },
    "tray": {
        // "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        "timezone": "Europe/Rome",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}"
    },
    "backlight": {
        "format": "{icon} {percent}%",
        "format-icons": ["", "", "", "", "", "", "", "", ""]
    },
    "battery": {
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["", "", "", "", ""]
    },
    "network": {
        "format-wifi": " {signalStrength}%",
        "format-ethernet": "{essid}",
        "tooltip-format": "{essid}",
        "format-linked": "{ifname} (No IP) ",
        "format-disconnected": "Disconnected ⚠",
        "format-alt": "{essid}"
    },
   "wireplumber": {
        "format": "{icon} {volume}%",
        "format-muted": "",
        "format-icons": ["", "", ""]
    },
    "custom/weather": {
        "format": "{}",
        "exec": "curl 'https://wttr.in/Viareggio?M&format=%c+%t'",
        "interval": 1800
    }
}

